export const lofiSongData = [
  { index: 0, name: "lofi1", fileName: "lofi1.mp3" },
  { index: 1, name: "lofi10", fileName: "lofi10.mp3" },
  { index: 2, name: "lofi11", fileName: "lofi11.mp3" },
  { index: 3, name: "lofi12", fileName: "lofi12.mp3" },
  { index: 4, name: "lofi13", fileName: "lofi13.mp3" },
  { index: 5, name: "lofi14", fileName: "lofi14.mp3" },
  { index: 6, name: "lofi15", fileName: "lofi15.mp3" },
  { index: 7, name: "lofi16", fileName: "lofi16.mp3" },
  { index: 8, name: "lofi17", fileName: "lofi17.mp3" },
  { index: 9, name: "lofi18", fileName: "lofi18.mp3" },
  { index: 10, name: "lofi19", fileName: "lofi19.mp3" },
  { index: 11, name: "lofi2", fileName: "lofi2.mp3" },
  { index: 12, name: "lofi20", fileName: "lofi20.mp3" },
  { index: 13, name: "lofi3", fileName: "lofi3.mp3" },
  { index: 14, name: "lofi4", fileName: "lofi4.mp3" },
  { index: 15, name: "lofi5", fileName: "lofi5.mp3" },
  { index: 16, name: "lofi6", fileName: "lofi6.mp3" },
  { index: 17, name: "lofi7", fileName: "lofi7.mp3" },
  { index: 18, name: "lofi8", fileName: "lofi8.mp3" },
  { index: 19, name: "lofi9", fileName: "lofi9.mp3" },
];
